usb_camera_node:
  ros__parameters:
    camera_device_v4l_url: $(var camera_path)  # /dev/v4l/by-id/...
    camera_info_url: "package://usb_camera/config/camera_info.yaml"
    image_topic: "usb_camera/image/compressed"
    image_raw_topic: "usb_camera/image_raw"
    camera_info_topic: "usb_camera/camera_info"
    frame_id: "camera_optical_frame"

    max_fail_count: 5                 # 连续失败的最大次数，超过该次数后将尝试重启摄像头 
    v4l2_buffers_requested_count: 4   # 请求的V4L2缓冲区数量
    restart_time: 0.5                 # 重启摄像头的时间间隔，单位为秒
    frame_timeout_time: 0.1           # 等待摄像头帧的超时时间，单位为秒

    image_width: 1280
    image_height: 720
    frame_rate: 60
    exposure_time_mode: 1             # 0: 自动曝光(映射为	V4L2_EXPOSURE_APERTURE_PRIORITY), 1: 手动曝光 (V4L2_EXPOSURE_MANUAL)
    exposure_time: 170
    brightness: 60
    contrast: 50
    saturation: 60
